# Netlify configuration for Vite
[build]
  command = "npm run build"
  publish = "dist"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  NODE_VERSION = "18.17.0"

# Default headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"